// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CourseSideBar: typeof import('./src/components/CourseSideBar.vue')['default']
    CourseTopBar: typeof import('./src/components/CourseTopBar.vue')['default']
    DueCountdown: typeof import('./src/components/DueCountdown.vue')['default']
    HomeworkCard: typeof import('./src/components/HomeworkCard.vue')['default']
    IUilBars: typeof import('~icons/uil/bars')['default']
    IUilBookAlt: typeof import('~icons/uil/book-alt')['default']
    IUilFacebook: typeof import('~icons/uil/facebook')['default']
    IUilGithub: typeof import('~icons/uil/github')['default']
    IUilHome: typeof import('~icons/uil/home')['default']
    IUilMapMarkerInfo: typeof import('~icons/uil/map-marker-info')['default']
    IUilMoon: typeof import('~icons/uil/moon')['default']
    IUilPlus: typeof import('~icons/uil/plus')['default']
    IUilPlusCircle: typeof import('~icons/uil/plus-circle')['default']
    IUilSun: typeof import('~icons/uil/sun')['default']
    IUilUser: typeof import('~icons/uil/user')['default']
    IUilWrench: typeof import('~icons/uil/wrench')['default']
    JudgeStatus: typeof import('./src/components/JudgeStatus.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    SampleCodeBlock: typeof import('./src/components/SampleCodeBlock.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}

export { }
