// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    CourseSideBar: typeof import('./src/components/CourseSideBar.vue')['default']
    CourseTopBar: typeof import('./src/components/CourseTopBar.vue')['default']
    DueCountdown: typeof import('./src/components/DueCountdown.vue')['default']
    HomeworkCard: typeof import('./src/components/HomeworkCard.vue')['default']
    HomeworkForm: typeof import('./src/components/HomeworkForm.vue')['default']
    IUilAngleDoubleLeft: typeof import('~icons/uil/angle-double-left')['default']
    IUilAngleDoubleRight: typeof import('~icons/uil/angle-double-right')['default']
    IUilBars: typeof import('~icons/uil/bars')['default']
    IUilBookAlt: typeof import('~icons/uil/book-alt')['default']
    IUilCheckCircle: typeof import('~icons/uil/check-circle')['default']
    IUilConstructor: typeof import('~icons/uil/constructor')['default']
    IUilEdit: typeof import('~icons/uil/edit')['default']
    IUilFacebook: typeof import('~icons/uil/facebook')['default']
    IUilGithub: typeof import('~icons/uil/github')['default']
    IUilHome: typeof import('~icons/uil/home')['default']
    IUilLeftArrowToLeft: typeof import('~icons/uil/left-arrow-to-left')['default']
    IUilMapMarkerInfo: typeof import('~icons/uil/map-marker-info')['default']
    IUilMoon: typeof import('~icons/uil/moon')['default']
    IUilPlusCircle: typeof import('~icons/uil/plus-circle')['default']
    IUilSetting: typeof import('~icons/uil/setting')['default']
    IUilSun: typeof import('~icons/uil/sun')['default']
    IUilTimesCircle: typeof import('~icons/uil/times-circle')['default']
    IUilUser: typeof import('~icons/uil/user')['default']
    JudgeStatus: typeof import('./src/components/JudgeStatus.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    PaginationButtons: typeof import('./src/components/PaginationButtons.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostForm: typeof import('./src/components/PostForm.vue')['default']
    ProblemAllowedLanguageSelector: typeof import('./src/components/Problem/Forms/ProblemAllowedLanguageSelector.vue')['default']
    ProblemCard: typeof import('./src/components/Problem/ProblemCard.vue')['default']
    ProblemDescriptionForm: typeof import('./src/components/Problem/Forms/ProblemDescriptionForm.vue')['default']
    ProblemForm: typeof import('./src/components/Problem/ProblemForm.vue')['default']
    ProblemTestdataDescriptionModal: typeof import('./src/components/Problem/Forms/ProblemTestdataDescriptionModal.vue')['default']
    SampleCodeBlock: typeof import('./src/components/SampleCodeBlock.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SideBarLink: typeof import('./src/components/SideBarLink.vue')['default']
    SkeletonCard: typeof import('./src/components/SkeletonCard.vue')['default']
    SkeletonPost: typeof import('./src/components/SkeletonPost.vue')['default']
    SkeletonTable: typeof import('./src/components/SkeletonTable.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UiSpinner: typeof import('./src/components/ui-spinner.vue')['default']
  }
}

export { }
