// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CourseSideBar: typeof import('./src/components/CourseSideBar.vue')['default']
    CourseTopBar: typeof import('./src/components/CourseTopBar.vue')['default']
    DueCountdown: typeof import('./src/components/DueCountdown.vue')['default']
    HomeworkCard: typeof import('./src/components/HomeworkCard.vue')['default']
    IUilBars: typeof import('~icons/uil/bars')['default']
    IUilBookAlt: typeof import('~icons/uil/book-alt')['default']
    IUilConstructor: typeof import("~icons/uil/constructor")["default"];
    IUilHome: typeof import('~icons/uil/home')['default']
    IUilInfCircle: typeof import("~icons/uil/inf-circle")["default"];
    IUilInfoCircle: typeof import("~icons/uil/info-circle")["default"];
    IUilInfpCircle: typeof import("~icons/uil/infp-circle")["default"];
    IUilInfpoCircle: typeof import("~icons/uil/infpo-circle")["default"];
    IUilMapMarkerInfo: typeof import('~icons/uil/map-marker-info')['default']
    IUilMapMarkInfo: typeof import("~icons/uil/map-mark-info")["default"];
    IUilMoon: typeof import('~icons/uil/moon')['default']
    IUilNewspaper: typeof import("~icons/uil/newspaper")["default"];
    IUilNinja: typeof import("~icons/uil/ninja")["default"];
    IUilSun: typeof import('~icons/uil/sun')['default']
    IUilUser: typeof import('~icons/uil/user')['default']
    IUilUserCircle: typeof import("~icons/uil/user-circle")["default"];
    IUilWrench: typeof import('~icons/uil/wrench')['default']
    JudgeStatus: typeof import('./src/components/JudgeStatus.vue')['default']
    NavBar: typeof import("./src/components/NavBar.vue")["default"];
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}

export { }
