// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./../components/CodeEditor.vue')['default']
    CourseSideBar: typeof import('./../components/CourseSideBar.vue')['default']
    CourseTopBar: typeof import('./../components/CourseTopBar.vue')['default']
    DueCountdown: typeof import('./../components/DueCountdown.vue')['default']
    HomeworkCard: typeof import('./../components/HomeworkCard.vue')['default']
    HomeworkForm: typeof import('./../components/HomeworkForm.vue')['default']
    JudgeStatus: typeof import('./../components/JudgeStatus.vue')['default']
    MarkdownRenderer: typeof import('./../components/MarkdownRenderer.vue')['default']
    PaginationButtons: typeof import('./../components/PaginationButtons.vue')['default']
    PostCard: typeof import('./../components/PostCard.vue')['default']
    PostForm: typeof import('./../components/PostForm.vue')['default']
    ProblemAllowedLanguageSelector: typeof import('./../components/Problem/Forms/ProblemAllowedLanguageSelector.vue')['default']
    ProblemCard: typeof import('./../components/Problem/ProblemCard.vue')['default']
    ProblemDescriptionForm: typeof import('./../components/Problem/Forms/ProblemDescriptionForm.vue')['default']
    ProblemForm: typeof import('./../components/Problem/ProblemForm.vue')['default']
    ProblemTestdataDescriptionModal: typeof import('./../components/Problem/Forms/ProblemTestdataDescriptionModal.vue')['default']
    SampleCodeBlock: typeof import('./../components/SampleCodeBlock.vue')['default']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    SideBarLink: typeof import('./../components/SideBarLink.vue')['default']
    SkeletonCard: typeof import('./../components/SkeletonCard.vue')['default']
    SkeletonPost: typeof import('./../components/SkeletonPost.vue')['default']
    SkeletonTable: typeof import('./../components/SkeletonTable.vue')['default']
    TopBar: typeof import('./../components/TopBar.vue')['default']
    UiSpinner: typeof import('./../components/ui-spinner.vue')['default']
  }
}

export { }
