// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementCard: typeof import('./../components/Announcement/AnnouncementCard.vue')['default']
    AnnouncementForm: typeof import('./../components/Announcement/AnnouncementForm.vue')['default']
    CodeEditor: typeof import('./../components/CodeEditor.vue')['default']
    CourseSideBar: typeof import('./../components/CourseSideBar.vue')['default']
    CourseTopBar: typeof import('./../components/CourseTopBar.vue')['default']
    DataStatusWrapper: typeof import('./../components/DataStatusWrapper.vue')['default']
    DueCountdown: typeof import('./../components/DueCountdown.vue')['default']
    HomeworkCard: typeof import('./../components/Homework/HomeworkCard.vue')['default']
    HomeworkForm: typeof import('./../components/Homework/HomeworkForm.vue')['default']
    JudgeStatus: typeof import('./../components/JudgeStatus.vue')['default']
    LanguageMultiSelect: typeof import('./../components/Problem/Forms/LanguageMultiSelect.vue')['default']
    LoginSection: typeof import('./../components/LoginSection.vue')['default']
    MarkdownRenderer: typeof import('./../components/MarkdownRenderer.vue')['default']
    PaginationButtons: typeof import('./../components/PaginationButtons.vue')['default']
    ProblemCard: typeof import('./../components/Problem/ProblemCard.vue')['default']
    ProblemDescriptionForm: typeof import('./../components/Problem/Forms/ProblemDescriptionForm.vue')['default']
    ProblemForm: typeof import('./../components/Problem/ProblemForm.vue')['default']
    ProblemMultiSelect: typeof import('./../components/Homework/Fields/ProblemMultiSelect.vue')['default']
    ProblemTestdataDescriptionModal: typeof import('./../components/Problem/Forms/ProblemTestdataDescriptionModal.vue')['default']
    SampleCodeBlock: typeof import('./../components/SampleCodeBlock.vue')['default']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    SideBarLink: typeof import('./../components/SideBarLink.vue')['default']
    SkeletonCard: typeof import('./../components/SkeletonCard.vue')['default']
    SkeletonPost: typeof import('./../components/SkeletonPost.vue')['default']
    SkeletonTable: typeof import('./../components/SkeletonTable.vue')['default']
    SystemAnnouncements: typeof import('./../components/SystemAnnouncements.vue')['default']
    TopBar: typeof import('./../components/TopBar.vue')['default']
    UiDialog: typeof import('./../components/ui-dialog.vue')['default']
    UiSpinner: typeof import('./../components/ui-spinner.vue')['default']
  }
}

export { }
