// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./../components/CodeEditor.vue')['default']
    CourseSideBar: typeof import('./../components/CourseSideBar.vue')['default']
    CourseTopBar: typeof import('./../components/CourseTopBar.vue')['default']
    DueCountdown: typeof import('./../components/DueCountdown.vue')['default']
    HomeworkCard: typeof import('./../components/HomeworkCard.vue')['default']
    HomeworkForm: typeof import('./../components/HomeworkForm.vue')['default']
    IUilAngleDoubleLeft: typeof import('~icons/uil/angle-double-left')['default']
    IUilAngleDoubleRight: typeof import('~icons/uil/angle-double-right')['default']
    IUilAngleDown: typeof import('~icons/uil/angle-down')['default']
    IUilAngleUp: typeof import('~icons/uil/angle-up')['default']
    IUilBars: typeof import('~icons/uil/bars')['default']
    IUilBookAlt: typeof import('~icons/uil/book-alt')['default']
    IUilChartLine: typeof import('~icons/uil/chart-line')['default']
    IUilEdit: typeof import('~icons/uil/edit')['default']
    IUilFileUploadAlt: typeof import('~icons/uil/file-upload-alt')['default']
    IUilHome: typeof import('~icons/uil/home')['default']
    IUilMapMarkerInfo: typeof import('~icons/uil/map-marker-info')['default']
    IUilMoon: typeof import('~icons/uil/moon')['default']
    IUilPlusCircle: typeof import('~icons/uil/plus-circle')['default']
    IUilRepeat: typeof import('~icons/uil/repeat')['default']
    IUilSun: typeof import('~icons/uil/sun')['default']
    IUilTimesCircle: typeof import('~icons/uil/times-circle')['default']
    IUilUser: typeof import('~icons/uil/user')['default']
    IUilWrench: typeof import('~icons/uil/wrench')['default']
    JudgeStatus: typeof import('./../components/JudgeStatus.vue')['default']
    MarkdownRenderer: typeof import('./../components/MarkdownRenderer.vue')['default']
    PaginationButtons: typeof import('./../components/PaginationButtons.vue')['default']
    PostCard: typeof import('./../components/PostCard.vue')['default']
    PostForm: typeof import('./../components/PostForm.vue')['default']
    ProblemAllowedLanguageSelector: typeof import('./../components/Problem/Forms/ProblemAllowedLanguageSelector.vue')['default']
    ProblemCard: typeof import('./../components/Problem/ProblemCard.vue')['default']
    ProblemDescriptionForm: typeof import('./../components/Problem/Forms/ProblemDescriptionForm.vue')['default']
    ProblemForm: typeof import('./../components/Problem/ProblemForm.vue')['default']
    ProblemTestdataDescriptionModal: typeof import('./../components/Problem/Forms/ProblemTestdataDescriptionModal.vue')['default']
    SampleCodeBlock: typeof import('./../components/SampleCodeBlock.vue')['default']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    SideBarLink: typeof import('./../components/SideBarLink.vue')['default']
    SkeletonCard: typeof import('./../components/SkeletonCard.vue')['default']
    SkeletonPost: typeof import('./../components/SkeletonPost.vue')['default']
    SkeletonTable: typeof import('./../components/SkeletonTable.vue')['default']
    TopBar: typeof import('./../components/TopBar.vue')['default']
    UiSpinner: typeof import('./../components/ui-spinner.vue')['default']
  }
}

export { }
